"""add github installation and repository tables

Revision ID: 408d8d1c2f19
Revises: c068660cda7c
Create Date: 2026-03-20 22:51:06.704779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408d8d1c2f19'
down_revision: Union[str, Sequence[str], None] = 'c068660cda7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.String(), nullable=False),
    sa.Column('account_login', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_index('ix_installations_user_id', 'github_installations', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repositories_github_repo_id', 'repositories', ['github_repo_id'], unique=True)
    op.create_index('ix_repositories_installation_id', 'repositories', ['installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repositories_installation_id', table_name='repositories')
    op.drop_index('ix_repositories_github_repo_id', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_installations_user_id', table_name='github_installations')
    op.drop_table('github_installations')
    # ### end Alembic commands ###
