"""add pull_requests table

Revision ID: b38d3662121d
Revises: 408d8d1c2f19
Create Date: 2026-03-21 22:54:20.250006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38d3662121d'
down_revision: Union[str, Sequence[str], None] = '408d8d1c2f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_repo_commit', 'pull_requests', ['repo_id', 'commit_sha'], unique=True)
    op.create_index('ix_pr_repo_number', 'pull_requests', ['repo_id', 'pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pr_repo_number', table_name='pull_requests')
    op.drop_index('ix_pr_repo_commit', table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
